#!/usr/bin/env bash
# Arguments: $APP
# Installs a package specified by the `CONTAINER_PACKAGE` env var

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname $0)/../common/functions"

echo "=====> post-release-buildstep"

#CMD="cat > gm && \
#      dpkg -s CONTAINER_PACKAGE > /dev/null 2>&1 || \
#        (apt-get update && apt-get install -y CONTAINER_PACKAGE && apt-get clean)"

#ID=$(docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
#test $(docker wait $ID) -eq 0
#docker commit $ID $IMAGE > /dev/null
