#!/usr/bin/env bash
# Arguments: $APP
# Runs gulp in our container

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x

source "$(dirname $0)/../common/functions"

APP="$1"
IMAGE="dokku/$APP"

dokku_log_info1" pre-deploy"

#dokku_log_info1 "Running gulp"
#id=$(docker run -d $IMAGE /bin/bash -c "cd /app && gulp default")
#test $(docker wait $id) -eq 0
#docker commit $id $IMAGE > /dev/null
#dokku_log_info1 "Building UI Complete")
