#!/usr/bin/env bash
# Arguments: $APP
# Installs the graphicsmagick package into the container

set -eo pipefail; [[ $DOKKU_TRACE ]] && set -x
source "$(dirname $0)/../common/functions"

dokku_log_info1" pre-release-buildstep"

#CMD="cat > gm && \
#      dpkg -s graphicsmagick > /dev/null 2>&1 || \
#        (apt-get update && apt-get install -y graphicsmagick && apt-get clean)"

#ID=$(docker run -i -a stdin $IMAGE /bin/bash -c "$CMD")
#test $(docker wait $ID) -eq 0
#docker commit $ID $IMAGE > /dev/null
